name: anni_mpris_service
description: D-Bus MPRIS controls for Linux.
version: 0.0.2
homepage: https://anni.rs
repository: https://github.com/ProjectAnni/mpris_service

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.5.0"

platforms:
  linux:

dependencies:
  dbus: ^0.7.6
